### ISSUE TITLE
Project Invitation

### ISSUE THREAD

**Issue by ghost** [secure-for-ai/goktls#1]
Hey, bro.
I'm extending the Go standard library crypto/tls.
Would you be interested in helping implement the kernel TLS part?
If you're interested, please join us.

https://gitlab.com/go-extension/tls

**Comment by 0-haha** [comment]
> Hey, bro. I'm extending the Go standard library crypto/tls. Would you be interested in helping implement the kernel TLS part? If you're interested, please join us.
> 
> https://gitlab.com/go-extension/tls

I am interested in your project, and I think it is better to merge two projects into one. Unfortunately, I really don't have time to work on it.

You can simply do a diff of two repos and import the new added code as this repo is developed on top of the Go standard library crypto/tls with 100% compatibility.

**Comment by ghost** [comment]
Yes, I have completed the merger.

But there may still be some problems. Can you give me your gitlab account and I will pull you into the project?

I will commit to the ktls branch later

**Comment by 0-haha** [comment]
You can add me. https://gitlab.com/0-haha
I think the issue might be the boring ssl. My repo keeps the boring ssl implementation. The idea is to make the repo consistent with the upstream so that merging code from the upstream will be much easier.

To achieve that, the code in internal can hooks the boring ssl to a dummy implementation. This makes the repo compiled, but boring ssl is never enabled.

**Comment by ghost** [comment]
Invited

The problem may be with readKernelRecord because I incorporated ktlsReadRecord into this function

I haven't actually tested it, and if n of recvmsg is less than 0, there may be some errors.

Can you take a look at it?
Look at the ktls branch. For now, kernel TLS is a beta feature and will not be merged into the master branch

**Comment by 0-haha** [comment]
You can use this repo to test KTLS (https://github.com/secure-for-ai/goktls_examples). You only need to modify the go.mod by replacing the goktls to your repo.

Currently, I disable readKernelRecord in TLS 1.3 if the kernel < 5.19. This is because I found the kernel randomly drops the package.

> if n of recvmsg is less than 0, there may be some errors.

recvmsg is a system call https://linux.die.net/man/2/recvmsg

> These calls return the number of bytes received, or -1 if an error occurred. The return value will be 0 when the peer has performed an orderly shutdown.

This means, if err != nil, the function should return immediately. Otherwise, n is greater than or equal to 0.

**Comment by ghost** [comment]
> You can use this repo to test KTLS (https://github.com/secure-for-ai/goktls_examples). You only need to modify the go.mod by replacing the goktls to your repo.
> 
> Currently, I disable readKernelRecord in TLS 1.3 if the kernel < 5.19. This is because I found the kernel randomly drops the package.
> 
> > if n of recvmsg is less than 0, there may be some errors.
> 
> recvmsg is a system call https://linux.die.net/man/2/recvmsg
> 
> > These calls return the number of bytes received, or -1 if an error occurred. The return value will be 0 when the peer has performed an orderly shutdown.
> 
> This means, if err != nil, the function should return immediately. Otherwise, n is greater than or equal to 0.

Hi, I added AES CCM's crypto suite to my latest commit. Does the kernel support cipher suites for AES_128_CCM_8 ？

**Comment by 0-haha** [comment]
https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/tls.h#L61

It supports, but this ciphersuite is not popular, and it's hard to test.

**Comment by ghost** [comment]
The thing is, there are very few websites that use CCM.

I tested Microsoft, Cloudflare, Apple, Google, Aliyun.
None of them are supportive.

But the good news is that wireshark can decrypt the traffic, and I can verify that my implementation is normal.

**Comment by ghost** [comment]
It appears that the kernel does not support AES_128_CCM with tag size 8

**Comment by ghost** [comment]
Do you know that AES CCM, SM4, ARIA these crypto suites are added on top of those kernel versions?

**Comment by 0-haha** [comment]
Look at the header file https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/tls.h#L61

Some of them are supported.

**Comment by ghost** [comment]
> Look at the header file https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/tls.h#L61
> 
> Some of them are supported.

I just want to know which version of the kernel adds CCM support.

**Comment by 0-haha** [comment]
> > Look at the header file https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/tls.h#L61
> > Some of them are supported.
> 
> I just want to know which version of the kernel adds CCM support.

To be honest, I don't know. Even if the header file adds the CCM support, the implementation might be buggy. That's why I disable TLS 1.3 RX on kernel < 5.19.

I would say you have to manually test it. If it works, then it works. I think you should focus on Kernel 5.15, 5.19, 6.1. 5.15 and 5.19 are supported by Ubuntu LTS. 6.1 is the LTS version supported by Linux Community.

**Comment by ghost** [comment]
> > > Look at the header file https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/tls.h#L61
> > > Some of them are supported.
> > 
> > 
> > I just want to know which version of the kernel adds CCM support.
> 
> To be honest, I don't know. Even if the header file adds the CCM support, the implementation might be buggy. That's why I disable TLS 1.3 RX on kernel < 5.19.
> 
> I would say you have to manually test it. If it works, then it works. I think you should focus on Kernel 5.15, 5.19, 6.1. 5.15 and 5.19 are supported by Ubuntu LTS. 6.1 is the LTS version supported by Linux Community.

So can u help me?

**Comment by ghost** [comment]
I have completed the check of AES CCM.
Can you perfect the kernel calls for SM4 and ARIA cipher suites?

**Comment by 0-haha** [comment]
No, I can't. I don't have time to do that.

**Comment by ghost** [comment]
> No, I can't. I don't have time to do that.

Okay, I'll try to do it. Thank you.
